### ISSUE TITLE
[Question] Correct way to update access token in createHTTPClient

### ISSUE THREAD

**Issue by mukulhase** [mobxjs/mst-gql#82] opened 2019-08-14 23:09 UTC
I'm using MST-GQL in my app and I have a "currentUser" store where I have a login function which receives and sets the access token. I want to be able to use this access token in the "Auth Bearer" header for all further requests. How do I set the header _after_ the RootStore has been initialised?

**Comment by chrisdrackett** [comment] 2019-08-14 23:56
the way I'm currently handling this is that I have a auth context outside of MST that I use to handle auth. I only start to render the `mst-gql` provider after I have the token.

This works for me because none of my graphQL is accessible without a user, but this might not be the case for you.

@mweststrate is there a way to update the `gqlHttpClient` after a store is setup? If not, maybe this is a feature we should add!

**Comment by mweststrate** [comment] 2019-08-16 20:17
If this is specifically about setting additional headers, I think we could extend the `QueryOptions` interface to support additional settings for that (e.g. a `headers` map). Most parts of the api already support passing an object with this config in, so I think that would also solve this case

**Comment by odjhey** [comment] 2019-09-11 02:23
@mweststrate  but the current [httpclient](https://github.com/prisma/graphql-request) does not support adding headers in every request. from the issues list of graphql-request, they suggested to re-instantiate the client every time headers change. Looking at our src, the httpClient is passed as a store's environment through some dependency injection.

This may be a MST specific question, but can we change those injected dependencies during runtime? I'm assuming no, since they are immutable.

how do you think should we proceed without moving out from graphql-request?

**Comment by mweststrate** [comment] 2019-09-11 09:40
I think you could create your own graphql-request wrapper (the api is
pretty small anyway), which would allow you to set headers for the next
request, and does the new client creation under the hood? When setting up
mst-gql you can than configure it to use your graphql-request-wrapper
instead of the built in implementation

**Comment by chrisdrackett** [comment] 2019-09-19 15:40
@odjhey can you post your solution for this?

**Comment by RXminuS** [comment] 2019-09-25 14:21
It seems you can actually just call `getEnv(self).gqlHttpClient.setHeaders({authorization: "bearer token"})` in for instance a handler that listens for token/user changes or after loading in localStorage data in an `afterCreate`.

**Comment by RXminuS** [comment] 2019-09-26 15:16
We can write a little example that showcases how to do it with a simple API (sign-in/out) flow?

**Comment by odjhey** [comment] 2019-09-28 09:00
> @odjhey can you post your solution for this?

hellow, sorry I was out for a while. I believe @RXminuS 's solution works way better and a lot simpler. But here goes nothing.

```js
  const [h, setH] = useState(
    (() => {
      let req = ""
      return {
        setReq: (newReq: any) => {
          req = newReq
        },
        req: (query: any, variables: any) => {
          const client = new GraphQLClient("http://localhost:3001/graphql", {
            headers: { "X-Custom": req }
          })
          return client.request(query, variables)
        }
      }
    })()
  )
```

I have a modified copy of example-1
https://github.com/odjhey/mst-gql/tree/example-6/examples/6-custom-http-handler

**Comment by odjhey** [comment] 2019-10-24 02:18
Hello @mukulhase , can we close this issue?

**Closed** 2019-10-24 03:38 UTC

**Comment by fullofcaffeine** [comment] 2019-11-05 20:45
I have a related question -- is the client setup to automatically send cookies? I'm having an issue where cookies are not being sent when the gql http client makes the requests to the `/graphql`  endpoint. Both the web server and the api server run from the same domain and port, so shouldn't be a CORS problem. Any hints?

**Comment by fullofcaffeine** [comment] 2019-11-05 21:54
Actually, the problem is the passing of cookies from the client over to the server when the same code that runs on the client runs on the server. It seems `graphql-client` does not support transparent passing of cookies from the client, so it's not isomorphic. It seems Apollo Link supports the SSR cookie use-case out-of-the-box: https://stackoverflow.com/questions/51995187/how-to-access-cookie-in-server-side-data-fetch-for-isomorphic-react-app. 

If anyone has any hints on how to solve it, I'd be grateful.

**Comment by fullofcaffeine** [comment] 2019-11-05 22:45
Nevermind, I accomplished what I wanted by passing the cookie header value from the express request object over to the `graphqlHttpClient` header options when instantiating it on the server.
