### ISSUE TITLE
SSR with custom app, how to hydrate with the pre-fetched data and avoid a refetch?

### ISSUE THREAD

**Issue by fullofcaffeine** [mobxjs/mst-gql#129] opened 2019-10-19 06:43 UTC
Hi!

I'm trying to setup `mst-gql` for SSR in a custom React app of mine. It's based off https://github.com/manuelbieh/react-ssr-setup, but with the Redux stuff removed. I've seen the examples in the README and in the nextjs app, and I **did manage** to fetch and render from the server.

The problem though, is that it's not clear how to send the snapshot data to the client so that it can hydrate taking it into account, so that the data is not fetched again. Right now, my app fetches in the server (using `getDataFromTree` and `getSnapshot` and passing it to the store created as initial data), the page then loads with the data pre-populated, only to be interrupted with a "Loading..." widget (part of the same React component that was rendered on the server) only to load everything again...

If anyone could point me to the right direction here, I'd be very grateful.

Thanks in advance!

**Comment by zenflow** [comment] 2019-10-19 13:30
Seems to be a duplicate of #95 which should be fixed already.. 

- make sure you're using the latest version of `mst-gql`
- make sure you're using the `ssr: true` option when initializing the root store (necessary on both server and client)
- let us know what the issue was (or if it's still an issue).. we might need to improve documentation here

**Comment by fullofcaffeine** [comment] 2019-10-19 23:52
Hi @zenflow, thanks for the prompt reply!

There was indeed a mistake in my setup -- I was not setting the `ssr` flag to true on both ends. But that wasn't the main problem. There was a key piece missing from my SSR setup: passing data to the client from the server. 

What I ended up doing was to get the snapshot data in the server, convert it to JSON (using `JSON.stringify` and rendering it in the returned HTML like so:

```typescript
const serverRenderer: any = () => async (req: express.Request, res: express.Response, next) => {
  const store = initializeStore(true);

  const comp =
    <StoreContext.Provider value={store}>
      <Router location={req.url} context={routerContext}>
          <HelmetProvider context={helmetContext}>
            <ThemeProvider theme={theme}>
              <App />
            </ThemeProvider>
          </HelmetProvider>
      </Router>
    </StoreContext.Provider>;

  const sheets = new ServerStyleSheets();
  const content = await getDataFromTree(sheets.collect(comp), store);
  const initialState = getSnapshot<RootStoreType>(store);
  const css = sheets.toString();

  return res.send(
    '<!doctype html>' +
    renderToString(
      <Html
        css={[res.locals.assetPath('bundle.css'), res.locals.assetPath('vendor.css')]}
        helmetContext={helmetContext}
        scripts={[res.locals.assetPath('bundle.js'), res.locals.assetPath('vendor.js')]}
        inlineStyle={css}
        state={JSON.stringify(initialState)}
      >
        {content}
      </Html>
    )
  );
};

Then in the actual HTML template renderer, I do:

```
                <script
                    // eslint-disable-next-line react/no-danger
                    dangerouslySetInnerHTML={{
                        // TODO: Add jsesc/stringify here
                        // see: https://twitter.com/HenrikJoreteg/status/1143953338284703744
                        __html: `window.__PRELOADED_STATE__ = ${state}`,
                    }}
                />

```

Now it seems to work fine. Maybe this could be added to the documentation, as it's currently assumed that SSR will be used with nextjs from what I've seen (since that's the only concrete example available).

Thanks!

**Comment by fullofcaffeine** [comment] 2019-10-21 18:28
Closing this as the original issue has been solved. There are a few observations above and a question that'd like to discuss, but there's no rush. Thanks!

**Closed** 2019-10-21 18:27 UTC

**Comment by fullofcaffeine** [comment] 2019-10-23 21:08
Is anyone else also doing SSR with `mst-gql` in a custom non-nextjs app? I'd just like to know if exposing the snapshot in the window is the "recommended" way of sharing the snapshot data with the client-side. It does seem to work well.

**Comment by fullofcaffeine** [comment] 2019-11-07 21:19
*ping* :)

**Comment by zenflow** [comment] 2019-11-07 21:32
@fullofcaffeine I haven't built a non-next.js SSR app in years, but I think that is how I did it. That's also the way next.js does it. I don't see any problem with doing it that way. Hope that helps.
